### ISSUE TITLE
openscenario 2.0: 139 SIGSEGV ERROR

### ISSUE THREAD

**Issue by XiaoFei9704** [guardstrikelab/scenario_runner#3]
**Describe the bug**
This problem occurs occasionally.
Either running openscenario or openscenario2 will report an error of 139 on the first run after starting Carla, but the second run and subsequent runs are normal. 

**Screenshots**

![2023-05-22 11-14-06 的屏幕截图](https://github.com/guardstrikelab/scenario_runner/assets/28669749/f1c7de52-202c-420d-9337-db8decb36c2b)
![2023-05-24 15-40-55 的屏幕截图](https://github.com/guardstrikelab/scenario_runner/assets/28669749/577f447a-4f7e-44c0-8a3f-fe7a41ec729c)

**Desktop (please complete the following information):**
 - OS:Ubuntu 20.04
 - CARLA Version CARLA 0.9.13
 - Python version 3.8.10
 - Version 0.9.13

**Comment by hsiang-lee** [comment]
https://osc2studio.online
